#! /bin/sh

java -Xms2048m -Xmx2048m -cp classes cs224n.assignments.WordAlignmentTester -dataPath /afs/ir.stanford.edu/class/cs224n/pa1/data -model cs224n.wordaligner.$1 -evalSet $2 -trainSentences $3 -verbose
